#!/bin/sh
go-bindata -pkg=bindata -o=src/bindata/bindata.go --ignore=".*.go|.*.less|\.module-cache|.*.un~|\.git|.DS_Store|jsx" assets/...
go-bindata -pkg=debug -debug=true -o=src/bindata/debug/bindata_debug.go --ignore=".*.go|.*.less|\.module-cache|.*.un~|.DS_Store|jsx" assets/...
